apiVersion: v1
kind: Service
metadata:
  name: count
spec:
  ports:
  - port: 5000
  selector:
    app: count
  clusterIP: None
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: count
spec:
  selector:
    matchLabels:
      app: count
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: count
    spec:
      containers:
      - image: count-web-app
        imagePullPolicy: Never
        name: count
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name:  FLASK_ENV
          value: production
        - name:  DATABASE_USER
          value: root
        - name:  DATABASE_PASSWORD
          value: password
        - name:  DATABASE_HOST
          value: mysql
        - name: DATABASE_PORT
          value: "3306"
        - name:  DATABASE_NAME
          value: count_db
        ports:
        - containerPort: 5000
          name: count
